version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: skoot_postgres
    environment:
      POSTGRES_USER: skoot_user
      POSTGRES_PASSWORD: skoot_password
      POSTGRES_DB: skoot_transportation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skoot_user -d skoot_transportation"]
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer:4.8.1
    container_name: skoot_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: skoot_network